# fly.toml app configuration file generated for thp-fake-eventbrite on 2023-05-16T12:13:20+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "thp-fake-eventbrite"
primary_region = "cdg"
console_command = "/rails/bin/rails console"

[env]
  PW = "$PW"
  USER = "$USER"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
